"""Shared helpers for the black-box tests of the host scripts.

Every test here runs a script from ``scripts/`` as a subprocess and asserts only
on what a caller can observe: stdout, stderr, and exit status.  Nothing imports,
sources, or greps a script's text, so the same tests must keep passing when a
script is rewritten in another language.

A script under test sees exactly one PATH entry: a sandbox ``bin/`` directory
holding fake executables plus symlinks to the few real system tools the script
legitimately needs.  A real docker or podman on the machine can therefore never
leak into a test, and no test needs a container engine or the network.

Stdlib only, Python 3.9-compatible.
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "scripts"

# The ambient PATH, captured once, is only ever used to LOCATE a named system
# tool.  It is never handed to a script under test.
REAL_PATH = os.environ.get("PATH", os.defpath)

# The separator the fakes used to join a recorded argv with.  Records are JSON
# now, so that an argument containing a newline survives; the name is kept
# because it was part of this module's surface.
ARG_SEP = "\x00"

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def strip_ansi(text: str) -> str:
    """The text without the colour escapes the scripts print to a terminal."""
    return _ANSI.sub("", text)


def host_is_wsl() -> bool:
    """True when /proc/version names microsoft, which is what open-url reads."""
    try:
        return "microsoft" in Path("/proc/version").read_text(errors="replace").lower()
    except OSError:
        return False


WSL_HOST = host_is_wsl()
NOT_ON_WSL = (
    "open-url decides it is on WSL from /proc/version as well as from "
    "WSL_DISTRO_NAME, and this host's /proc/version says microsoft. The "
    "non-WSL branches cannot be reached from outside the script here; they "
    "run in CI, which is real Linux."
)


_FAKE_TEMPLATE = '''#!/usr/bin/env python3
"""A fake executable generated by tests/host/fakes.py. Records argv, replies."""
import json
import os
import sys

SPEC = json.loads({spec!r})

args = sys.argv[1:]

# One JSON object per line.  A NUL-joined record would be ambiguous as soon as
# an argument contains a newline, and the self-test suite routinely passes a
# whole multi-line shell script as a single argument to `bash -lc`.
record = {{"argv": args}}
if SPEC["record_env"]:
    record["env"] = {{
        name: os.environ[name] for name in SPEC["record_env"] if name in os.environ
    }}
with open(SPEC["calls"], "a") as handle:
    handle.write(json.dumps(record) + "\\n")

counts_path = SPEC["calls"] + ".counts"
try:
    with open(counts_path) as handle:
        counts = json.load(handle)
except (IOError, OSError, ValueError):
    counts = {{}}

reply = SPEC["default"]
for index, rule in enumerate(SPEC["rules"]):
    want = rule["args"]
    if rule["match"] == "prefix":
        hit = args[: len(want)] == want
    elif rule["match"] == "contains":
        hit = all(any(needle in arg for arg in args) for needle in want)
    else:
        hit = all(word in args for word in want)
    if hit and rule.get("times") is not None:
        # A rule with a budget stops matching once it is spent, so a later
        # rule (or the default) answers the identical call the next time.
        seen = counts.get(str(index), 0)
        if seen >= rule["times"]:
            hit = False
        else:
            counts[str(index)] = seen + 1
            with open(counts_path, "w") as handle:
                json.dump(counts, handle)
    if hit:
        reply = rule
        break

sys.stdout.write(reply["stdout"])
sys.stderr.write(reply["stderr"])
sys.exit(reply["exit"])
'''

MATCH_MODES = ("prefix", "all", "contains")


def rule(
    args: Sequence[str],
    stdout: str = "",
    stderr: str = "",
    exit_code: int = 0,
    match: str = "prefix",
    times: Optional[int] = None,
) -> Dict[str, object]:
    """One argv-dependent reply for a fake.

    ``match='prefix'`` fires when argv starts with ``args``; ``match='all'``
    fires when every word in ``args`` appears anywhere in argv as a whole
    argument; ``match='contains'`` fires when every string in ``args`` appears
    as a *substring* of some argument.  ``contains`` is what addresses a
    command sent as one argument, as in ``bash -lc '<a whole script>'``.

    ``times=N`` spends the rule after N matching calls; the identical call then
    falls through to the rules below it.  That is the only way to model a
    command that fails a few times and then starts working, such as the
    readiness probe a retry loop repeats with an unchanging argv.
    """
    if match not in MATCH_MODES:
        raise ValueError(
            "match must be one of {}, not {!r}".format(", ".join(MATCH_MODES), match)
        )
    return {
        "args": list(args),
        "stdout": stdout,
        "stderr": stderr,
        "exit": exit_code,
        "match": match,
        "times": times,
    }


def _lines(text: str) -> List[str]:
    """Split on newline only.

    str.splitlines() would also split on a lone carriage return, which would
    hide exactly the kind of stray \\r that base-image-digest strips on purpose.
    """
    parts = text.split("\n")
    return parts[:-1] if parts and parts[-1] == "" else parts


class Run(NamedTuple):
    status: int
    stdout: str
    stderr: str

    @property
    def out(self) -> str:
        return strip_ansi(self.stdout)

    @property
    def err(self) -> str:
        return strip_ansi(self.stderr)

    @property
    def out_lines(self) -> List[str]:
        return _lines(strip_ansi(self.stdout))

    @property
    def err_lines(self) -> List[str]:
        return _lines(strip_ansi(self.stderr))

    def report(self) -> str:
        return "exit {}\n--- stdout ---\n{}--- stderr ---\n{}".format(
            self.status, self.stdout, self.stderr
        )


class Sandbox:
    """A throwaway PATH holding only fakes and explicitly allowed real tools."""

    def __init__(self, root: Path):
        self.root = root
        self.bin = root / "bin"
        self.calls = root / "calls"
        self.bin.mkdir(parents=True)
        self.calls.mkdir(parents=True)
        (root / "home").mkdir()
        # The interpreter behind every `#!/usr/bin/env python3`: the fakes' and
        # the scripts' under test.  It is the one running this suite, not
        # whatever `python3` is first on PATH, for two reasons.  A pyenv or asdf
        # shim there is a bash script, and the sandbox has no bash.  And a suite
        # run as `python3.9 -m unittest` to check the 3.9 floor should run the
        # scripts under 3.9 too, which a PATH lookup does not promise.
        (self.bin / "python3").symlink_to(sys.executable)

    def link(self, *names: str) -> None:
        """Make the real system tool of each name reachable on the sandbox PATH."""
        for name in names:
            target = shutil.which(name, path=REAL_PATH)
            if target is None:
                raise RuntimeError(
                    "the test needs the system tool {!r}, which is not on PATH".format(name)
                )
            link = self.bin / name
            if not link.exists():
                link.symlink_to(target)

    def fake(
        self,
        name: str,
        stdout: str = "",
        stderr: str = "",
        exit_code: int = 0,
        rules: Sequence[Dict[str, object]] = (),
        record_env: Sequence[str] = (),
    ) -> Path:
        """Create a fake executable that records its argv and replies as told.

        ``record_env`` names environment variables to record alongside each
        call, readable afterwards with ``recorded_envs`` / ``last_recorded_env``.
        """
        spec = json.dumps(
            {
                "calls": str(self.calls / name),
                "rules": list(rules),
                "record_env": list(record_env),
                "default": {
                    "args": [],
                    "stdout": stdout,
                    "stderr": stderr,
                    "exit": exit_code,
                    "match": "prefix",
                },
            }
        )
        path = self.bin / name
        path.write_text(_FAKE_TEMPLATE.format(spec=spec))
        path.chmod(0o755)
        return path

    def remove(self, name: str) -> None:
        """Take a command off the sandbox PATH."""
        path = self.bin / name
        if path.exists() or path.is_symlink():
            path.unlink()

    def called(self, name: str) -> bool:
        return (self.calls / name).exists()

    def _records(self, name: str) -> List[Dict[str, object]]:
        """Every recorded call to the named fake, in order, as raw records."""
        path = self.calls / name
        if not path.exists():
            return []
        return [json.loads(line) for line in path.read_text().splitlines() if line]

    def argv(self, name: str) -> List[List[str]]:
        """The argv of each call to the named fake, in order."""
        return [list(record["argv"]) for record in self._records(name)]

    def last_argv(self, name: str) -> List[str]:
        calls = self.argv(name)
        if not calls:
            raise AssertionError("{} was never called".format(name))
        return calls[-1]

    def recorded_envs(self, name: str) -> List[Dict[str, str]]:
        """The recorded environment of each call, in order.

        Only the variables named in the fake's ``record_env`` appear, and only
        those the call actually had set.
        """
        return [dict(record.get("env", {})) for record in self._records(name)]

    def last_recorded_env(self, name: str) -> Dict[str, str]:
        envs = self.recorded_envs(name)
        if not envs:
            raise AssertionError("{} was never called".format(name))
        return envs[-1]

    def environ(self, **overrides: Optional[str]) -> Dict[str, str]:
        """A minimal environment whose PATH is the sandbox and nothing else."""
        env = {
            "PATH": str(self.bin),
            "HOME": str(self.root / "home"),
            "LC_ALL": "C",
        }
        for key, value in overrides.items():
            if value is None:
                env.pop(key, None)
            else:
                env[key] = value
        return env


class ScriptTestCase(unittest.TestCase):
    """Base for one script's tests: a fresh sandbox per test, no shared state."""

    script = ""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory(prefix="ros2-host-test-")
        self.addCleanup(tmp.cleanup)
        self.sandbox = Sandbox(Path(tmp.name))

    def run_script(
        self,
        *args: str,
        env: Optional[Dict[str, str]] = None,
        script: Optional[str] = None,
        **overrides: Optional[str]
    ) -> Run:
        path = SCRIPTS / (script or self.script)
        # Bytes, decoded by hand: text mode would translate a lone \r into \n
        # and hide exactly the kind of stray carriage return these tests pin.
        proc = subprocess.run(
            [str(path)] + list(args),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.DEVNULL,
            cwd=str(self.sandbox.root),
            env=self.sandbox.environ(**overrides) if env is None else env,
            check=False,
            timeout=60,
        )
        return Run(
            proc.returncode,
            proc.stdout.decode("utf-8", errors="replace"),
            proc.stderr.decode("utf-8", errors="replace"),
        )

    def assertHas(self, run: Run, needle: str, where: str = "stdout") -> None:
        text = run.out if where == "stdout" else run.err
        self.assertIn(needle, text, "{!r} not in {}\n{}".format(needle, where, run.report()))

    def assertLacks(self, run: Run, needle: str, where: str = "stdout") -> None:
        text = run.out if where == "stdout" else run.err
        self.assertNotIn(needle, text, "{!r} in {}\n{}".format(needle, where, run.report()))

    def assertStatus(self, run: Run, expected: int) -> None:
        self.assertEqual(expected, run.status, run.report())
