"""Shared helpers for the black-box tests of the host scripts.

Every test here runs a script from ``scripts/`` as a subprocess and asserts only
on what a caller can observe: stdout, stderr, and exit status.  Nothing imports,
sources, or greps a script's text, so the same tests must keep passing when a
script is rewritten in another language.

A script under test sees exactly one PATH entry: a sandbox ``bin/`` directory
holding fake executables plus symlinks to the few real system tools the script
legitimately needs.  A real docker or podman on the machine can therefore never
leak into a test, and no test needs a container engine or the network.

Stdlib only, Python 3.9-compatible.
"""

import json
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "scripts"

# The ambient PATH, captured once, is only ever used to LOCATE a named system
# tool.  It is never handed to a script under test.
REAL_PATH = os.environ.get("PATH", os.defpath)

ARG_SEP = "\x00"

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def strip_ansi(text: str) -> str:
    """The text without the colour escapes the scripts print to a terminal."""
    return _ANSI.sub("", text)


def host_is_wsl() -> bool:
    """True when /proc/version names microsoft, which is what open-url reads."""
    try:
        return "microsoft" in Path("/proc/version").read_text(errors="replace").lower()
    except OSError:
        return False


WSL_HOST = host_is_wsl()
NOT_ON_WSL = (
    "open-url decides it is on WSL from /proc/version as well as from "
    "WSL_DISTRO_NAME, and this host's /proc/version says microsoft. The "
    "non-WSL branches cannot be reached from outside the script here; they "
    "run in CI, which is real Linux."
)


_FAKE_TEMPLATE = '''#!/usr/bin/env python3
"""A fake executable generated by tests/host/fakes.py. Records argv, replies."""
import json
import sys

SPEC = json.loads({spec!r})

with open(SPEC["calls"], "a") as handle:
    handle.write("\\x00".join(sys.argv[1:]) + "\\n")

args = sys.argv[1:]
reply = SPEC["default"]
for rule in SPEC["rules"]:
    want = rule["args"]
    if rule["match"] == "prefix":
        hit = args[: len(want)] == want
    else:
        hit = all(word in args for word in want)
    if hit:
        reply = rule
        break

sys.stdout.write(reply["stdout"])
sys.stderr.write(reply["stderr"])
sys.exit(reply["exit"])
'''


def rule(
    args: Sequence[str],
    stdout: str = "",
    stderr: str = "",
    exit_code: int = 0,
    match: str = "prefix",
) -> Dict[str, object]:
    """One argv-dependent reply for a fake.

    ``match='prefix'`` fires when argv starts with ``args``; ``match='all'``
    fires when every word in ``args`` appears anywhere in argv.
    """
    if match not in ("prefix", "all"):
        raise ValueError("match must be 'prefix' or 'all', not {!r}".format(match))
    return {
        "args": list(args),
        "stdout": stdout,
        "stderr": stderr,
        "exit": exit_code,
        "match": match,
    }


def _lines(text: str) -> List[str]:
    """Split on newline only.

    str.splitlines() would also split on a lone carriage return, which would
    hide exactly the kind of stray \\r that base-image-digest strips on purpose.
    """
    parts = text.split("\n")
    return parts[:-1] if parts and parts[-1] == "" else parts


class Run(NamedTuple):
    status: int
    stdout: str
    stderr: str

    @property
    def out(self) -> str:
        return strip_ansi(self.stdout)

    @property
    def err(self) -> str:
        return strip_ansi(self.stderr)

    @property
    def out_lines(self) -> List[str]:
        return _lines(strip_ansi(self.stdout))

    @property
    def err_lines(self) -> List[str]:
        return _lines(strip_ansi(self.stderr))

    def report(self) -> str:
        return "exit {}\n--- stdout ---\n{}--- stderr ---\n{}".format(
            self.status, self.stdout, self.stderr
        )


class Sandbox:
    """A throwaway PATH holding only fakes and explicitly allowed real tools."""

    def __init__(self, root: Path):
        self.root = root
        self.bin = root / "bin"
        self.calls = root / "calls"
        self.bin.mkdir(parents=True)
        self.calls.mkdir(parents=True)
        (root / "home").mkdir()
        # The fakes' own interpreter, named by their `#!/usr/bin/env python3`.
        self.link("python3")

    def link(self, *names: str) -> None:
        """Make the real system tool of each name reachable on the sandbox PATH."""
        for name in names:
            target = shutil.which(name, path=REAL_PATH)
            if target is None:
                raise RuntimeError(
                    "the test needs the system tool {!r}, which is not on PATH".format(name)
                )
            link = self.bin / name
            if not link.exists():
                link.symlink_to(target)

    def fake(
        self,
        name: str,
        stdout: str = "",
        stderr: str = "",
        exit_code: int = 0,
        rules: Sequence[Dict[str, object]] = (),
    ) -> Path:
        """Create a fake executable that records its argv and replies as told."""
        spec = json.dumps(
            {
                "calls": str(self.calls / name),
                "rules": list(rules),
                "default": {
                    "args": [],
                    "stdout": stdout,
                    "stderr": stderr,
                    "exit": exit_code,
                    "match": "prefix",
                },
            }
        )
        path = self.bin / name
        path.write_text(_FAKE_TEMPLATE.format(spec=spec))
        path.chmod(0o755)
        return path

    def remove(self, name: str) -> None:
        """Take a command off the sandbox PATH."""
        path = self.bin / name
        if path.exists() or path.is_symlink():
            path.unlink()

    def called(self, name: str) -> bool:
        return (self.calls / name).exists()

    def argv(self, name: str) -> List[List[str]]:
        """The argv of each call to the named fake, in order."""
        path = self.calls / name
        if not path.exists():
            return []
        lines = path.read_text().splitlines()
        return [[] if line == "" else line.split(ARG_SEP) for line in lines]

    def last_argv(self, name: str) -> List[str]:
        calls = self.argv(name)
        if not calls:
            raise AssertionError("{} was never called".format(name))
        return calls[-1]

    def environ(self, **overrides: Optional[str]) -> Dict[str, str]:
        """A minimal environment whose PATH is the sandbox and nothing else."""
        env = {
            "PATH": str(self.bin),
            "HOME": str(self.root / "home"),
            "LC_ALL": "C",
        }
        for key, value in overrides.items():
            if value is None:
                env.pop(key, None)
            else:
                env[key] = value
        return env


class ScriptTestCase(unittest.TestCase):
    """Base for one script's tests: a fresh sandbox per test, no shared state."""

    script = ""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory(prefix="ros2-host-test-")
        self.addCleanup(tmp.cleanup)
        self.sandbox = Sandbox(Path(tmp.name))

    def run_script(
        self,
        *args: str,
        env: Optional[Dict[str, str]] = None,
        script: Optional[str] = None,
        **overrides: Optional[str]
    ) -> Run:
        path = SCRIPTS / (script or self.script)
        # Bytes, decoded by hand: text mode would translate a lone \r into \n
        # and hide exactly the kind of stray carriage return these tests pin.
        proc = subprocess.run(
            [str(path)] + list(args),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.DEVNULL,
            cwd=str(self.sandbox.root),
            env=self.sandbox.environ(**overrides) if env is None else env,
            check=False,
            timeout=60,
        )
        return Run(
            proc.returncode,
            proc.stdout.decode("utf-8", errors="replace"),
            proc.stderr.decode("utf-8", errors="replace"),
        )

    def assertHas(self, run: Run, needle: str, where: str = "stdout") -> None:
        text = run.out if where == "stdout" else run.err
        self.assertIn(needle, text, "{!r} not in {}\n{}".format(needle, where, run.report()))

    def assertLacks(self, run: Run, needle: str, where: str = "stdout") -> None:
        text = run.out if where == "stdout" else run.err
        self.assertNotIn(needle, text, "{!r} in {}\n{}".format(needle, where, run.report()))

    def assertStatus(self, run: Run, expected: int) -> None:
        self.assertEqual(expected, run.status, run.report())
